# CHANGE THIS
fullname: Valerian Hall-Chen
position: Scientist
department: Institute of High Performance Computing
university: A*STAR

building: Connexis # optional
street: 1 Fusionopolis Way # optional
city: # optional
postcode: 138632 # optional
country: Singapore # optional

email: valerian_hall-chen [at] ihpc.a-star.edu.sg
secondary: # optional

formurl: https://formspree.io/myynorgy
# url: https://valerian-chen.github.io/valerian.hall-chen.com

# DON'T CHANGE THIS
collections:
  papers:
  bookchapters:
  conferences:
